-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
	local physics = { data =
	{ 
		
		["racingtrack_outer"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "out_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 65535, maskBits = 65535, groupIndex = 0 },
                    shape = {   -501, -375  ,  -371, -289  ,  -416, -253  }
                    }
                     ,
                    {
                    pe_fixture_id = "out_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 65535, maskBits = 65535, groupIndex = 0 },
                    shape = {   351, -233  ,  283, -301  ,  505, -374  ,  397, -203  }
                    }
                     ,
                    {
                    pe_fixture_id = "out_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 65535, maskBits = 65535, groupIndex = 0 },
                    shape = {   -501, -375  ,  -320, -305  ,  -371, -289  }
                    }
                     ,
                    {
                    pe_fixture_id = "out_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 65535, maskBits = 65535, groupIndex = 0 },
                    shape = {   -91, -221  ,  -146, -243  ,  -264, -297  ,  101, -277  ,  26, -240  ,  -36, -218  }
                    }
                     ,
                    {
                    pe_fixture_id = "out_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 65535, maskBits = 65535, groupIndex = 0 },
                    shape = {   505, -374  ,  259, -313  ,  213, -305  ,  -264, -297  ,  -320, -305  ,  -501, -375  }
                    }
                     ,
                    {
                    pe_fixture_id = "out_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 65535, maskBits = 65535, groupIndex = 0 },
                    shape = {   259, -313  ,  505, -374  ,  283, -301  }
                    }
                     ,
                    {
                    pe_fixture_id = "out_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 65535, maskBits = 65535, groupIndex = 0 },
                    shape = {   -264, -297  ,  213, -305  ,  101, -277  }
                    }
                    
                    
                    
		}
		
		, 
		["racingtrack_inner"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "inner_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -237, -165  ,  -189, -136  ,  -304, -64  ,  -299, -139  ,  -279, -165  }
                    }
                     ,
                    {
                    pe_fixture_id = "inner_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -119, -114  ,  -80, 214  ,  -158, 214  ,  -320, -11  ,  -304, -64  ,  -189, -136  }
                    }
                     ,
                    {
                    pe_fixture_id = "inner_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   304, 217  ,  264, 229  ,  199, 224  ,  340, -33  ,  351, 71  ,  334, 169  ,  323, 199  }
                    }
                     ,
                    {
                    pe_fixture_id = "inner_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   114, 219  ,  81, -164  ,  143, -175  ,  319, -109  ,  340, -33  ,  199, 224  }
                    }
                     ,
                    {
                    pe_fixture_id = "inner_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   239, -182  ,  282, -156  ,  319, -109  ,  143, -175  ,  160, -190  }
                    }
                     ,
                    {
                    pe_fixture_id = "inner_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -339, 167  ,  -350, 113  ,  -339.33332824707, 50  ,  -320, -11  ,  -158, 214  ,  -249, 220  ,  -311, 212  ,  -325.33332824707, 200.66667175293  }
                    }
                     ,
                    {
                    pe_fixture_id = "inner_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -47, -117  ,  -2, 222  ,  -80, 214  ,  -119, -114  }
                    }
                     ,
                    {
                    pe_fixture_id = "inner_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   19, -128  ,  52, 224  ,  -2, 222  ,  -47, -117  }
                    }
                     ,
                    {
                    pe_fixture_id = "inner_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   52, 224  ,  55, -147  ,  81, -164  ,  114, 219  }
                    }
                     ,
                    {
                    pe_fixture_id = "inner_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   55, -147  ,  52, 224  ,  19, -128  }
                    }
                    
                    
                    
		}
		
		, 
		["racingtrack_outer2"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "out_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 65535, maskBits = 65535, groupIndex = 0 },
                    shape = {   -501, -375  ,  -371, -289  ,  -416, -253  }
                    }
                     ,
                    {
                    pe_fixture_id = "out_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 65535, maskBits = 65535, groupIndex = 0 },
                    shape = {   -501, -375  ,  -320, -305  ,  -371, -289  }
                    }
                     ,
                    {
                    pe_fixture_id = "out_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 65535, maskBits = 65535, groupIndex = 0 },
                    shape = {   -91, -221  ,  -146, -243  ,  -264, -297  ,  101, -277  ,  26, -240  ,  -36, -218  }
                    }
                     ,
                    {
                    pe_fixture_id = "out_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 65535, maskBits = 65535, groupIndex = 0 },
                    shape = {   -411, -73  ,  -416, -31  ,  -432, 23  ,  -449, 70  ,  -501, -375  ,  -423, -206  ,  -406, -149  }
                    }
                     ,
                    {
                    pe_fixture_id = "out_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 65535, maskBits = 65535, groupIndex = 0 },
                    shape = {   -425, -234  ,  -501, -375  ,  -416, -252  }
                    }
                     ,
                    {
                    pe_fixture_id = "out_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 65535, maskBits = 65535, groupIndex = 0 },
                    shape = {   239, 321  ,  324, 340  ,  31, 326  ,  170, 310  }
                    }
                     ,
                    {
                    pe_fixture_id = "out_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 65535, maskBits = 65535, groupIndex = 0 },
                    shape = {   283, -301  ,  397, -203  ,  351, -233  }
                    }
                     ,
                    {
                    pe_fixture_id = "out_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 65535, maskBits = 65535, groupIndex = 0 },
                    shape = {   -264, -297  ,  -320, -305  ,  -501, -375  ,  213, -305  ,  101, -277  }
                    }
                     ,
                    {
                    pe_fixture_id = "out_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 65535, maskBits = 65535, groupIndex = 0 },
                    shape = {   -423, -206  ,  -501, -375  ,  -425, -234  }
                    }
                     ,
                    {
                    pe_fixture_id = "out_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 65535, maskBits = 65535, groupIndex = 0 },
                    shape = {   -465, 128  ,  -501, -375  ,  -449, 70  }
                    }
                     ,
                    {
                    pe_fixture_id = "out_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 65535, maskBits = 65535, groupIndex = 0 },
                    shape = {   -431, 303  ,  -464, 165  ,  -441, 251  }
                    }
                     ,
                    {
                    pe_fixture_id = "out_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 65535, maskBits = 65535, groupIndex = 0 },
                    shape = {   324, 340  ,  -86, 330  ,  31, 326  }
                    }
                     ,
                    {
                    pe_fixture_id = "out_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 65535, maskBits = 65535, groupIndex = 0 },
                    shape = {   -501, -375  ,  259, -313  ,  213, -305  }
                    }
                     ,
                    {
                    pe_fixture_id = "out_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 65535, maskBits = 65535, groupIndex = 0 },
                    shape = {   324, 340  ,  -211, 333  ,  -86, 330  }
                    }
                     ,
                    {
                    pe_fixture_id = "out_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 65535, maskBits = 65535, groupIndex = 0 },
                    shape = {   433, -137  ,  465, 99  ,  449, -15  }
                    }
                     ,
                    {
                    pe_fixture_id = "out_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 65535, maskBits = 65535, groupIndex = 0 },
                    shape = {   -464, 165  ,  -501, -375  ,  -465, 128  }
                    }
                     ,
                    {
                    pe_fixture_id = "out_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 65535, maskBits = 65535, groupIndex = 0 },
                    shape = {   -505, 376  ,  -501, -375  ,  505, -374  ,  507, 378  }
                    }
                    
                    
                    
		}
		
		, 
		["racingtrack_outer1"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "out_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 65535, maskBits = 65535, groupIndex = 0 },
                    shape = {   505, -374  ,  423, -176  ,  397, -203  }
                    }
                     ,
                    {
                    pe_fixture_id = "out_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 65535, maskBits = 65535, groupIndex = 0 },
                    shape = {   -411, -73  ,  -416, -31  ,  -432, 23  ,  -449, 70  ,  -423, -206  ,  -406, -149  }
                    }
                     ,
                    {
                    pe_fixture_id = "out_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 65535, maskBits = 65535, groupIndex = 0 },
                    shape = {   -425, -234  ,  -502, -374  ,  -415, -255  }
                    }
                     ,
                    {
                    pe_fixture_id = "out_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 65535, maskBits = 65535, groupIndex = 0 },
                    shape = {   -425, -234  ,  -423, -206  ,  -505, 376  ,  -502, -374  }
                    }
                     ,
                    {
                    pe_fixture_id = "out_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 65535, maskBits = 65535, groupIndex = 0 },
                    shape = {   505, -374  ,  433, -137  ,  423, -176  }
                    }
                     ,
                    {
                    pe_fixture_id = "out_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 65535, maskBits = 65535, groupIndex = 0 },
                    shape = {   505, -374  ,  507, 378  ,  433, -137  }
                    }
                     ,
                    {
                    pe_fixture_id = "out_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 65535, maskBits = 65535, groupIndex = 0 },
                    shape = {   239, 321  ,  324, 340  ,  31, 326  ,  170, 310  }
                    }
                     ,
                    {
                    pe_fixture_id = "out_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 65535, maskBits = 65535, groupIndex = 0 },
                    shape = {   -465, 128  ,  -423, -206  ,  -449, 70  }
                    }
                     ,
                    {
                    pe_fixture_id = "out_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 65535, maskBits = 65535, groupIndex = 0 },
                    shape = {   -431, 303  ,  -505, 376  ,  -464, 165  ,  -441, 251  }
                    }
                     ,
                    {
                    pe_fixture_id = "out_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 65535, maskBits = 65535, groupIndex = 0 },
                    shape = {   324, 340  ,  507, 378  ,  -86, 330  ,  31, 326  }
                    }
                     ,
                    {
                    pe_fixture_id = "out_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 65535, maskBits = 65535, groupIndex = 0 },
                    shape = {   -464, 165  ,  -505, 376  ,  -465, 128  }
                    }
                     ,
                    {
                    pe_fixture_id = "out_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 65535, maskBits = 65535, groupIndex = 0 },
                    shape = {   -413, 322  ,  -505, 376  ,  -431, 303  }
                    }
                     ,
                    {
                    pe_fixture_id = "out_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 65535, maskBits = 65535, groupIndex = 0 },
                    shape = {   -351, 330  ,  -505, 376  ,  -413, 322  }
                    }
                     ,
                    {
                    pe_fixture_id = "out_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 65535, maskBits = 65535, groupIndex = 0 },
                    shape = {   -211, 333  ,  507, 378  ,  -505, 376  ,  -351, 330  }
                    }
                     ,
                    {
                    pe_fixture_id = "out_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 65535, maskBits = 65535, groupIndex = 0 },
                    shape = {   -86, 330  ,  507, 378  ,  -211, 333  }
                    }
                     ,
                    {
                    pe_fixture_id = "out_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 65535, maskBits = 65535, groupIndex = 0 },
                    shape = {   391, 333  ,  507, 378  ,  324, 340  }
                    }
                     ,
                    {
                    pe_fixture_id = "out_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 65535, maskBits = 65535, groupIndex = 0 },
                    shape = {   435, 297  ,  507, 378  ,  391, 333  }
                    }
                     ,
                    {
                    pe_fixture_id = "out_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 65535, maskBits = 65535, groupIndex = 0 },
                    shape = {   460, 179  ,  507, 378  ,  435, 297  }
                    }
                     ,
                    {
                    pe_fixture_id = "out_boundary", density = 2, friction = 0.5, bounce = 0.3, 
                    filter = { categoryBits = 65535, maskBits = 65535, groupIndex = 0 },
                    shape = {   465, 99  ,  507, 378  ,  460, 179  }
                    }
                    
                    
                    
		}
		
	} }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
	
	function physics:get(name)
		return unpack(self.data[name])
	end

	function physics:getFixtureId(name, index)
                return self.data[name][index].pe_fixture_id
	end
	
	return physics;
end

return M

